# Generated by Django 5.2.5 on 2025-09-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpmap', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpContact',
        ),
    ]
