# Generated by Django 5.2.5 on 2025-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0002_periodcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodcycle',
            name='cycle_length',
            field=models.IntegerField(blank=True, help_text='Average cycle length in days', null=True),
        ),
    ]
