# Generated by Django 5.2.5 on 2025-09-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0003_alter_periodcycle_cycle_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodcycle',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Enter your symptoms during this period', null=True),
        ),
    ]
