# Generated by Django 5.2.5 on 2025-09-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0004_periodcycle_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodcycle',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
    ]
