# Generated by Django 5.2.5 on 2025-09-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowapp', '0005_alter_periodcycle_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PeriodCycle',
        ),
    ]
