# Generated by Django 5.2.5 on 2025-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfortwall', '0002_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='other_text',
            field=models.TextField(blank=True),
        ),
    ]
