# Generated by Django 5.2.5 on 2025-09-22 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mongo_order_id', models.CharField(help_text='MongoEngine Order ID', max_length=64, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('items_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FlowFinds Order (record)',
                'verbose_name_plural': 'FlowFinds Orders (records)',
                'ordering': ['-created_at'],
            },
        ),
    ]
